# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Primeiro Workflow Teste

on:
  pull_request:
    branches:
      - main

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout do código
        uses: actions/checkout@v4
    
      - name: Hello World
        run: echo "Helo World"

  
  discord-notificacao:
    runs-on: ubuntu-latest
    environment: github-automacao

    steps:
      - name: Notificacao discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content": "PR realizado com sucesso"}' \
          ${{ secrets.DISCORD_WEBHOOK }}

